#!/bin/bash
#
set -e
CONFIG="/home/sabnzbd/.sabnzbd/sabnzbd.ini"
. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

update() {
service subsonic stop
ver1=`wget -q http://sabnzbd.org/download/ -O - | \grep sourceforge\.net | grep Linux | \sed 's/.*href=\"\(.*\)\".*/\1/' | sed 's/.*-\(.*\)-.*/\1/'`
if [ "$ver1" == "" ]; then
    exit
fi
wget -q -nv http://downloads.sourceforge.net/project/sabnzbdplus/sabnzbdplus/${ver1}/SABnzbd-${ver1}-src.tar.gz -O /tmp/sabnzbdplus.tar.gz
tar xzf /tmp/sabnzbdplus.tar.gz -C /tmp/
cp -fRa /tmp/SABnzbd-${ver1}/. /opt/SABnzbd/
rm -fR /tmp/sabnzbdplus.tar.gz
rm -fR /tmp/SABnzbd-${ver1}
chown sabnzbd:users /opt/SABnzbd -R
chmod 775 /opt/SABnzbd -R
}

getsettings() {
ver1=`wget -q http://www.subsonic.org/pages/download.jsp -O - | \grep subsonic-[0-9].[0-9].deb | \sed 's/.*href=\"\(.*\)\".*/\1/' | sed 's/^[^-]*=//' | sed 's/\(^subsonic\-\)\(.*\)\(\.deb\)/\2/'`
ver2=`grep -A 6 'Package: subsonic' /var/lib/dpkg/status  | grep ^Version: | sed 's/^[^-]*: //'`
ver3=`wget -q http://www.subsonic.org/pages/download.jsp -O - | \grep subsonic-[0-9].[0-9].beta[0-9].deb | \sed 's/.*href=\"\(.*\)\".*/\1/' | sed 's/^[^-]*=//' | sed 's/\(^subsonic\-\)\(.*\)\(\.deb\)/\2/'`


#ver2=0.7.00 #use to test if button shows if values do not match
if [ "$ver1" == "$ver2" ]; then
    xmlstarlet ed -L -u "//services/subsonic/update" -v 0 -n ${OMV_CONFIG_FILE}
else
    xmlstarlet ed -L -u "//services/subsonic/update" -v 1 -n ${OMV_CONFIG_FILE}
fi

if [ "$ver3" == "$ver2" ]; then
    xmlstarlet ed -L -u "//services/subsonic/bupdate" -v 0 -n ${OMV_CONFIG_FILE}
else
    xmlstarlet ed -L -u "//services/subsonic/bupdate" -v 1 -n ${OMV_CONFIG_FILE}
fi

if [ -f $CONFIG ]; then
	HOST=`grep -m 1 host $CONFIG | cut -d ' ' -f 3`
    if [ `grep -m 1 enable_https $CONFIG | cut -d ' ' -f 3` == "1" ]; then
		PORT=`grep -m1 https_port $CONFIG | cut -d ' ' -f 3`
	else
		PORT=`grep -m2 port $CONFIG | tail -n1 | cut -d ' ' -f 3`
	fi
else
	PORT="8080"
fi

xmlstarlet ed -L -u "//services/subsonic/port" -v $PORT -n ${OMV_CONFIG_FILE}
}

case "$2" in
  update)
    update
    ;;
  bupdate)
    bupdate
    ;;
  getsettings)
    getsettings
    ;;
  *)
    exit 1
esac
